import missedbot.handlers.menu as menu
import missedbot.handlers.start as start
import missedbot.handlers.presence_check as presence_check
import missedbot.handlers.add_student as add_student
import missedbot.handlers.add_group as add_group
import missedbot.handlers.add_discipline as add_discipline
import missedbot.handlers.del_student as del_student
import missedbot.handlers.discipline_to_group as discipline_to_group
import missedbot.handlers.interactive_report as interactive_report
import missedbot.handlers.download_report as download_report