class FirstBaseClass:
    ...

class SecondBaseClass:
    ...

class ThirdBaseClass:
    ...

class FirstTestClass(FirstBaseClass, ThirdBaseClass):
    ...

class SecondTestClass(SecondBaseClass):
    ...

class TopTestClass(FirstTestClass, SecondTestClass):
    ...